### ISSUE TITLE
Step sometime fails with `Error: fetch failed`

### ISSUE THREAD

**Issue by pedropombeiro** [darnfish/watchtower-update#56]
Hi. I very often get an error when running this step with the [following configuration](https://github.com/pedropombeiro/gitlab-dashboard/blob/main/.github/workflows/ci.yml#L231-L236):

```yaml
      - name: Deploy
        uses: darnfish/watchtower-update@v4
        with:
          url: "${{ secrets.WATCHTOWER_URL }}"
          api_token: "${{ secrets.WATCHTOWER_API_TOKEN }}"
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
```

<img width="1010" alt="image" src="https://github.com/user-attachments/assets/755bdb8f-5c8c-476f-ba56-705bef6f9a9b" />

[Link to failed job](https://github.com/pedropombeiro/gitlab-dashboard/actions/runs/12666610457/job/35298558899)

I don't see anything to go on in order to debug this issue. If I hit the HTTP endpoint of watchtower with `curl`, it works as expected.
